### ISSUE TITLE
How to use Athom 15W bulb custom component in Home-Assistant

### ISSUE THREAD

**Issue by Drizzt321** [jaddel/ESPHome#4]
Hi! Thanks for the work! Do you know how I'd go about adding in a custom ESPHome component in the Home-Assistant integration? I've done a ton of searches, but just can't seem to find anything on it.

**Comment by 10bn** [comment]
ESPHome and Homeassistant are two separate things. 

The custom light i created is used within Esphome and not in Homeassistant. 

ESPHome can provide controllable devices to Homeassistant. If you want to add an esphome device in Homeassistant you go to configuration --> Integrations --> Add Integration --> ESPHome.

If you know about Tasmota we could compare ESPHome to be similar as Tasmota. 

Since ESPHome does not natively support RBGWCT light. I tried to write a custom light component for esphome.
https://github.com/jaddel/ESPHome-Configurations/blob/master/Devices/Bulb%20Athom%2015W%20RGBWCT/athom_15w.h

I suggest that you read through this before you continue: https://esphome.io/guides/getting_started_hassio.html

The custom component will be included in the esphome yaml file: https://esphome.io/components/light/custom.html?highlight=custom%20light

**Comment by Drizzt321** [comment]
So apparently I can put include files in config/esphome/includes on HA, and ESPHome integration can pick them up. So I did so with the .h, and the used your YAML as a sample, and seem to have gotten it working. Yay. 

Except `color_interlock: true` isn't allowed/doesn't work, so it's it has the RGB on, and seems to crash now and then, or at least HA loses connection now and then, and so randomly it'll stop responding to HA, and no log messages are return to the log. I need to restart the logging connection and then it starts to work again.

It'll be a few weeks, but I might have to the time to try and hack away at it to get the color interlock working. 

ESPHome does work with RGBWW bulbs, https://esphome.io/components/light/rgbww.html, and my config mostly works, for some reason GPIO13, which I _think_ is marked as inverted due to the Tasmota config showing it's PWM_I type, which according to my email with them is the WW, while GPIO5 is the CW. It's weird, when I have GPIO5 as the WW, I only get CW, no WW, when I swap them, GPIO13 as WW, I get WW. Or maybe I have that reversed, I need to go to bed rather than do some more flashing and testing again. It's all very confusing.

**Comment by 10bn** [comment]
I suggest you use tasmota since my code is not jet properly working and at the current stage I'm not able to fixt it since i had quite some help creating it. 

Check out these two links: https://tasmota.github.io/docs/Commands/   search for "setoption92" it will explain why this light is not woking with the esphome rgbww light. 
https://templates.blakadder.com/athom_LB01-15W-E27.html

**Comment by Drizzt321** [comment]
Yeah, I read in https://tasmota.github.io/docs/Lights/#pwm-ct and https://tasmota.github.io/docs/Lights/#channel-controlled-lights about the specifics. I asked Athom if they have any more details, since I can get it to _mostly_ work with the RGBWW component, just not ending up with both the WW and CW at once, and maybe they can point me to specific places in the Tasmota code, if they have them handy.

If not, I'll have to take the time to dive into the Tasmota code, see how they're doing things, and perhaps port it over to ESPHome.
